Updates for openssl v3
dsully/perl-crypt-openssl-pkcs12 pull request #42
Opened 2023-08-11 20:21 UTC by timlegge

# Description

Please include a summary of the proposed improvement or addressed issue.
The biggest code change to support openssl v3 was the callback function changed.  However, due to https://github.com/openssl/openssl/issues/19092 changin the pk12 password is broken in all current openssl v3.x versions released.

Also, I exported the p12 file and recreated but I just noticed someone else may have a better command in #40.  The reall trouble is that the key for the ca is not included.  I had to set the daye to 2007 and do:

`openssl pkcs12 -export -inkey priv.pem -in cer1.pem -certfile cer2.pem -chain -CAfile cer2.pem -out certs/test.p12
`
Fixes/addresses (If applicable) # (issue)
#40 

## Type of change

Please delete options that are not relevant.

- [x ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] Any dependent changes have been merged and published in downstream modules
- [ x] Changes have been manually tested (please provide information on test platform using the fields below)

## Test / Development Platform Information

- Operating system and version
- Ubuntu 22.04.3 LTS
- Crypt::OpenSSL::PKCS12 version master
- Perl version v5.36.1
- OpenSSL version
- OpenSSL 3.0.2

Please see the issue template for a more information on provided the requested information.

2023-08-11 21:46 UTC, timlegge commented
Pushed a new version of the test.p12 with the friendlyname set so it is closer to the original if that matters

2023-08-24 16:54 UTC, timlegge commented
@GillesT78 what is 19092

2023-08-24 17:06 UTC, timlegge commented
Oh yeah, if memory serves that bug is fixed in the next version of OpenSSL.
No released version has it at this point in time. That's why the tests for
this module had to be modified.

On Thu, Aug 24, 2023, 2:00 PM Jonas Brømsø ***@***.***> wrote:

> Hi @timlegge <https://github.com/timlegge> I think it is this one:
> openssl/openssl#19092 <https://github.com/openssl/openssl/issues/19092>
>
> @GillesT78 <https://github.com/GillesT78> this repository is a Perl
> wrapper for a subset of OpenSSL functionality, that is propably why you do
> not recognize the .xs and .t files, these are Perl specific. The .t files
> are test files and the .xs file contains bindings to the OpenSSL C API
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dsully/perl-crypt-openssl-pkcs12/pull/42#issuecomment-1692088679>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH3N6YHCNBMRVPH2PC7INLXW6CBLANCNFSM6AAAAAA3NL23N4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-24 18:44 UTC, timlegge commented
> Hello timledgge
> 
> I don't find any information regarding the fix in the next version Do you know where I can find the fix ? in a specific branch ?
> 
> Regards Gilles

https://github.com/openssl/openssl/pull/20134 looks like it fixes the issue but I have not tested

2023-08-26 18:13 UTC, jonasbn commented
Hi @timlegge 

I am in the process of reviewing the PR and it looks good. However I cannot get the tests to pass.

- macOS ventura 13.4.1 (c) (22F770820d)
- Perl version v5.36.1
- OpenSSL version_ 1.1.1v

2023-08-26 18:18 UTC, jonasbn commented
@timlegge `Crypt::OpenSSL::Guess` should also be added to the: `Makefile.PL`

2023-08-26 19:11 UTC, timlegge commented
I will take a look see if I can see anything. Can you send me a copy of the
log?

On Sat, Aug 26, 2023, 3:13 PM Jonas Brømsø ***@***.***> wrote:

> Hi @timlegge <https://github.com/timlegge>
>
> I am in the process of reviewing the PR and it looks good. However I
> cannot get the tests to pass.
>
>    - macOS ventura 13.4.1 (c) (22F770820d)
>    - Perl version v5.36.1
>    - OpenSSL version_ 1.1.1v
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dsully/perl-crypt-openssl-pkcs12/pull/42#issuecomment-1694426939>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH3N6Y2PFII4SPKQVJY6JDXXI4FHANCNFSM6AAAAAA3NL23N4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-26 19:26 UTC, timlegge commented
@jonasbn can you run:

`perl -I blib/lib/ -I blib/arch/ t/pkcs12-string.t`

It will be easier to see what is failing

2023-08-26 19:44 UTC, timlegge commented
> Hi @timlegge
> 
> I am in the process of reviewing the PR and it looks good. However I cannot get the tests to pass.
> 
> * macOS ventura 13.4.1 (c) (22F770820d)
> * Perl version v5.36.1
> * OpenSSL version_ 1.1.1v

I did not realise that I have bot enabled the actions on my fork.  I am able to reproduce so I will take a look.

Tim

2023-08-26 19:47 UTC, jonasbn commented
Hi @timlegge 

Here is the output of the requested run

```
❯ carton exec -- perl -I blib/lib/ -I blib/arch/ t/pkcs12-string.t
1..29
ok 1 - use Crypt::OpenSSL::PKCS12;
ok 2
ok 3
ok 4 - utf8 string refused new_from_string()
ok 5
ok 6 - utf8 string refused in new_from_string()
# Attempting to read certificate string from file certs/test.p12
ok 7
ok 8
ok 9
ok 10
ok 11
ok 12
ok 13
ok 14
ok 15
ok 16
ok 17
ok 18 - PKCS object created
ok 19 - PEM certificate created
ok 20 - Asserting PEM key
ok 21 - Asserting mac
ok 22 - Asserting PKCS12 as string
PKCS12_newpass: testing foo
8101240320:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto/asn1/tasn_dec.c:1149:
8101240320:error:0D06C03A:asn1 encoding routines:asn1_d2i_ex_primitive:nested asn1 error:crypto/asn1/tasn_dec.c:713:
8101240320:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto/asn1/tasn_dec.c:646:Field=salt, Type=PBEPARAM
8101240320:error:0D0C706E:asn1 encoding routines:ASN1_item_unpack:decode error:crypto/asn1/asn_pack.c:60:
8101240320:error:23080072:PKCS12 routines:PKCS12_newpass:parse error:crypto/pkcs12/p12_npas.c:50:
not ok 23 - Changing password
#   Failed test 'Changing password'
#   at t/pkcs12-string.t line 105.
#
PKCS12_verify_mac:
# Looks like your test exited with 255 just after 23.
#
```

2023-08-26 20:07 UTC, timlegge commented
@jonasbn perfect thanks.  I suspect that the format of the file changed but I will take a closer look

2023-08-29 13:53 UTC, timlegge commented
@jonasbn - still trying to figure this out - but I may need to create different p12 files for certain versions.  I will keep looking.  The other option is to use openssl to generate a p12 for each test as part of the test.

2023-08-30 00:49 UTC, timlegge commented
So, the story here is that openssl has had issue with the pkcs12 "app" some changes over the versions have broken the format.  Between and across versions.

Right now I have copied the original version in to a certs/test_le_1.1.p12 and set the tests to use that file if the openssl version is less than or equal to 1.1.  That makes the tests work.  However I have a suspicion that a 1.1 version of openssl *may* not be able to create a pkcs12 file compatiable with the change password function

I will do some more testing.  It may take creating a test that creates a new pkcs12 file each time it is run to figure our where it breaks down

2023-08-31 13:12 UTC, timlegge commented
@jonasbn I have everything working except the MacOS action.  Unfortunately nothing I try seems to fix the issue and I have no real way to figur out what going on in MacOS (I don't run it)  

I will cleanup the PR because I have been just trying different approaches.  I suspect at this point it is either a bug specific to MasOS or that specific version of openSSL.

Do you have MacOS?  If so can you test once I clean up the PR?

2023-09-12 16:53 UTC, jonasbn commented
Hi @timlegge 

I can get the tests to pass locally.

I will make a few minor changes to the branch before merging it.

- I have commented in the unlinking of `t/scratch-csr.pem`
- I have updated the macOS GH Action, let's see if that works

2023-09-15 15:00 UTC, timlegge commented
I'm still not sure why the GitHub action fails for that PR. I need to pull back a commit that I put on it just recently to see if that was causing it but didn't do it right. I will have to take a closer look at the versioning on that Mac github action and see if there's anything that looks suspicious.

2023-09-20 17:45 UTC, gregoa commented
We are applying this PR in Debian (in the version from mid-August), but the two tests `t/pkcs12-string.t` and `t/pkcs12.t`are failing again against newer OpenSSL versions (3.0.11 and 3.1.3). Cf. https://bugs.debian.org/1052331

I've now updated our version of the patch to
```
    if ($major =~ /^3\./) {
        skip("OpenSSL 3.x cannot change pkcs12 passwords", 3);
```
in both `*.t`files.

2023-10-15 13:16 UTC, timlegge commented
@jonasbn I finally realise what is happening here for the macos tester.  It likely finds and builds for openssl version 3 but the Makefile forces 1.1 I will fix and rebase in the next few days

2023-10-17 00:40 UTC, timlegge commented
Having trouble getting Module::Install to do what I want.  Any objection to a PR to convert to Dist::Zilld based on perl-crypt-openssl-x509?

TIm

2023-10-17 04:52 UTC, jonasbn commented
hi @timlegge 

I use Dist::Zilla everywhere else, so a PR would be most welcome

2023-10-18 01:54 UTC, timlegge commented
@jonasbn can you approve the workflow to run.  I can still squash but I would like to see if this sorts the mac issue

2024-04-09 11:49 UTC, timlegge commented
Ping @jonasbn .

2024-04-11 02:15 UTC, timlegge commented
Still trying to sort out actions issues.

2024-04-15 07:54 UTC, jonasbn commented
Hi @timlegge 

I am unable to replicate the build errors locally, so I believe this to be an issue for the CI job on GitHub.

My suspicion is that this might be related to the writing of the temporary files. I can see that we are writing to both: `t/` and `certs/`, should we make this uniform.

And the use of `unlink` in `pkcs12-from-scratch.t` is both in the top and the bottom of the file, I think we should attempt to put these in the top, so we could push the generated files as artifacts for download and inspection - let me know what you think.

Secondly we could release a TRIAL and get some feedback from CPAN-testers, perhaps they can replicate the issue.

2024-04-15 08:25 UTC, jonasbn commented
@timlegge I believe we can remove the following lines from: `.github/workflows/macos.yml`

```yaml
      - name: install openssl
        run: |
          brew install openssl@1.1
```

The macOS runner is defaulting to OpenSSL version 3. (`3.2.1` to be exact).

What do you think?

2024-04-15 16:09 UTC, timlegge commented
> I am unable to replicate the build errors locally, so I believe this to be an issue for the CI job on GitHub.

I am glad you weren't able to replicate it. The GitHub actions are nice but sometimes cause problems on their own. 

> My suspicion is that this might be related to the writing of the temporary files. I can see that we are writing to both: `t/` and `certs/`, should we make this uniform.
I seem to remember something around. Get up actions and temporary files. I will have to take a look 

> And the use of `unlink` in `pkcs12-from-scratch.t` is both in the top and the bottom of the file, I think we should attempt to put these in the top, so we could push the generated files as artifacts for download and inspection - let me know what you think.

Yeah, it would be nice to be able to review some of those items when there are issues 

> Secondly we could release a TRIAL and get some feedback from CPAN-testers, perhaps they can replicate the issue.
Yep, that would help a lot. 

Tim

2024-04-15 16:10 UTC, timlegge commented
> @timlegge I believe we can remove the following lines from: `.github/workflows/macos.yml`
> 
> ```yaml
>       - name: install openssl
>         run: |
>           brew install openssl@1.1
> ```
> 
> The macOS runner is defaulting to OpenSSL version 3. (`3.2.1` to be exact).
> 
> Version 1 is deprecated, currently pointing to: `1.1.1w`
> 
> REF: https://formulae.brew.sh/formula/openssl@1.1
> 
> What do you think?

I think you are correct. When I went through I must have missed that one. Although I did specify Main for some of the installs, which we may want to go to the actual latest version.

Tim

2024-04-17 16:29 UTC, jonasbn requested changes
Hi @timlegge 

I have a few cosmetic suggestions. I believe I have review many of the proposed changes earlier, so I think the core functionality is in good state

I can see that you are proposing a migration from Module::Install to Dist::Zilla, so I guess we need to remove `inc/`

Let me know if you have any questions

2024-04-17 16:29 UTC, jonasbn commented on dist.ini
> +copyright_year = 2004-2021
Please bump the year

```suggestion
copyright_year = 2004-2024
```

2024-04-17 16:29 UTC, jonasbn commented on .github/workflows/cygwin.yml
> +      - name: Install Depends
Write this out

```suggestion
      - name: Install Dependencies
```

2024-04-17 16:29 UTC, jonasbn commented on .github/workflows/macos.yml
> +      - name: Install Depends
Write this out

```suggestion
      - name: Install Dependencies
```

2024-04-17 16:29 UTC, jonasbn commented on .github/workflows/msys2-mingw.yml
> +      - name: Install Depends
Write this out

```suggestion
      - name: Install Dependencies
```

2024-04-17 16:29 UTC, jonasbn commented on .github/workflows/windows.yml
> +      - name: Install Depends
Write this out

```suggestion
      - name: Install Dependencies
```

2024-04-18 00:15 UTC, timlegge commented
I think I fixed all the issues

2024-04-18 02:14 UTC, timlegge commented
also fixed msys2 action

2024-04-18 10:32 UTC, jonasbn approved these changes
This is approved.

Thanks @timlegge for your contribution and tireless efforts

2024-04-18 10:32 UTC, merged