set LDDLFLAGS by default in case library is installed elsewhere
dsully/perl-crypt-openssl-pkcs12 pull request #47
Opened 2024-06-08 18:35 UTC by timlegge

# Description

This sets LDDLFLAGS by default in case library is installed elsewhere

I was trouble shooting a HPUX issre where OpenSSL 1.1.1w  11 Sep 2023 in a non standard location and this was needed.  It should be required by default to catch cases when Crypt::OpenSSL::Guess finds another openssl version that is not installed by default

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] Changes have been manually tested (please provide information on test platform using the fields below)

## Test / Development Platform Information

- Operating system and version
- Crypt::OpenSSL::PKCS12 version  OpenSSL 1.1.1w
- Perl version: 5.26.2
- OpenSSL version HP UX

Ubuntu 24:04 and all the github actions pass

2024-06-12 06:11 UTC, jonasbn requested changes
Hi @timlegge 

Looks good, minor cosmetic requirement.

2024-06-12 06:11 UTC, jonasbn commented on Makefile.PL
> +  $args{LDDLFLAGS} = openssl_lib_paths() . " " . $Config{lddlflags};
Please replace double quotes with single quotes. 

Too many years with Perl::Critic, has made me allergic to double quotes

2024-06-12 06:11 UTC, jonasbn commented on maint/Makefile_header.PL
> +  $args{LDDLFLAGS} = openssl_lib_paths() . " " . $Config{lddlflags};
Please replace double quotes with single quotes. 

Too many years with Perl::Critic, has made me allergic to double quotes

2024-06-12 13:18 UTC, jonasbn approved these changes
LGTM @timlegge approved

2024-06-12 13:18 UTC, merged

2024-06-15 08:54 UTC, jonasbn commented
@timlegge as I understand this PR, I believe the addition would make sense in: [dsully/perl-crypt-openssl-x509](https://github.com/dsully/perl-crypt-openssl-x509) as well

What do you think?

2024-06-15 17:40 UTC, timlegge commented
> @timlegge as I understand this PR, I believe the addition would make sense in: [dsully/perl-crypt-openssl-x509](https://github.com/dsully/perl-crypt-openssl-x509) as well
> 
> What do you think?

I agree - just tested and it is require.  PR sent